name: doctor-management

services:
  postgres-db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: doctor_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
 